version: '3'

include:
  - ./docker-compose.fdn.yml

services:
  admin-api:
    build:
      context: .
      dockerfile: Dockerfile.dev.admin-api
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
      - PORT=8080
      - API_KEY_TOKEN=123456
      - JWT_SECRET=1234567
      - DB_NAME=nodite
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
    ports:
      - 8080:8080
      - 9229:9229
    volumes:
      - .:/app
      - type: tmpfs
        target: /app/node_modules
      - type: tmpfs
        target: /app/services/admin-api/node_modules
    depends_on:
      - postgres
    networks:
      - default
