version: "3"

services:
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    privileged: true
    environment:
      MYSQL_DATABASE: nodite
      # MYSQL_USER: root
      # MYSQL_PASSWORD: nodite
      MYSQL_ROOT_PASSWORD: nodite
    ports:
      - 3306:3306
    volumes:
      - ./volumes/mysql:/var/lib/mysql
    networks:
      - default

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    privileged: true
    ports:
      - 6379:6379
    volumes:
      - ./volumes/redis:/data
    networks:
      - default

  redis-commander:
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "6378:8081"
    depends_on:
      - redis
    networks:
      - default

  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    privileged: true
    environment:
      - PG_MAJOR
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nodite
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default

networks:
  default:
