version: '3'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      - PG_MAJOR
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nodite
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres-entrypoint.sh:/usr/local/bin/postgres-entrypoint.sh
      - ./volumes/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default

networks:
  default:
