name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: .nvmrc

      - name: Ensure dotenv
        run: |
          cp services/admin-api/.env.template services/admin-api/.env

      - name: Install dependencies
        run: npm ci --prefer-offline

      - name: Lint commit message
        run: npx commitlint --from=HEAD~1

      - name: Build packages
        run: npm run build

      - name: Lint packages
        run: npm run lint

      - name: Test packages
        run: npm test
